language: ruby
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
env:
  - RAILS_ENV=test
notifications:
  email: false
